# Generated by Django 4.0.5 on 2022-07-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_plan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='shortcut_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
