# Generated by Django 4.0.5 on 2022-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_video_url_alter_project_budget_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pay_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='settlement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
