# Generated by Django 4.0.5 on 2022-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
