# Generated by Django 4.0.5 on 2022-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_price_alter_project_target_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pk_uri',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
